# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

language: python
python:
  # - 2.7
  - 3.6

dist: xenial
services:
  - xvfb

# before_script:
#   - "export DISPLAY=:99.0"
#   - "sh -e /etc/init.d/xvfb start"
#   - sleep 3

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n testenv python=$TRAVIS_PYTHON_VERSION pip pytest numpy pandas scipy matplotlib scikit-learn
  - source activate testenv
  - pip install --upgrade python-coveralls pytest-cov codecov
  - pip install -r requirements.txt --upgrade
  - pip install tox-travis
  - python setup.py install

# command to run tests, e.g. python setup.py test
script:
  - coverage run --source feat -m py.test

after_success:
  - coveralls

# After you create the Github repo and add it to Travis, run the
# travis_pypi_setup.py script to finish PyPI deployment setup
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: ljchang
  password:
    secure: PLEASE_REPLACE_ME
  on:
    tags: true
    repo: cosanlab/feat
    python: 3.6
