# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Py-Feat
author: Eshin Jolly, Jin Hyun Cheong, Tiankang Xie
copyright: "2022"
logo: "images/logo/pyfeat_logo_small.png"
exclude_patterns            : [ README.md, _build, Thumbs.db, .DS_Store, "**.ipynb_checkpoints"]

execute:
  execute_notebooks         : off  # Whether to execute notebooks at build time. Must be one of ("auto", "force", "cache", "off")
  cache                     : ""    # A path to the jupyter cache that will be used to store execution artifacs. Defaults to `_build/.jupyter_cache/`
  # exclude_patterns          : [content/Download_Data.ipynb]   # A list of patterns to *skip* in execution (e.g. a notebook that takes a really long time)
  timeout                   : 30    # The maximum time (in seconds) each notebook cell is allowed to run.
  run_in_temp               : true # If `True`, then a temporary directory will be created and used as the command working directory (cwd),
                                    # otherwise the notebook's parent directory will be the cwd.
  allow_errors              : true # If `False`, when a code cell raises an error the execution is stopped, otherwise all cells are always run.
  stderr_output             : show  # One of 'show', 'remove', 'remove-warn', 'warn', 'error', 'severe'

#######################################################################################
# Parse and render settings
parse:
  myst_extended_syntax      : true  # enable MyST extended syntax support (see documents for details)
  myst_url_schemes          : [mailto, http, https]  # URI schemes that will be recognised as external URLs in Markdown links

#######################################################################################
# HTML-specific settings
html:
  favicon                   : "images/logo/favicon.ico"  # A path to a favicon image
  use_edit_page_button      : true  # Whether to add an "edit this page" button to pages. If `true`, repository information in repository: must be filled in
  use_repository_button     : true  # Whether to add a link to your repository button
  use_issues_button         : true  # Whether to add an "open an issue" button
  extra_navbar              : "" # Will be displayed underneath the left navbar.
  extra_footer              : "" # Will be displayed underneath the footer.
  google_analytics_id       : "UA-113777015-5" # A GA id that can be used to track book views.
  home_page_in_navbar       : false  # Whether to include your home page in the left Navigation Bar
  baseurl                   : "" # The base URL where your book will be hosted. Used for creating image previews and social links. e.g.: https://mypage.com/mybook/
  comments:
    hypothesis              : false
    utterances              : false

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true

#######################################################################################
# LaTeX-specific settings
latex:
  latex_engine              : pdflatex  # one of 'pdflatex', 'xelatex' (recommended for unicode), 'luatex', 'platex', 'uplatex'

#######################################################################################
# Launch button settings
launch_buttons:
  notebook_interface        : classic  # The interface interactive links will activate ["classic", "jupyterlab"]
  binderhub_url             : https://mybinder.org  # The URL of the BinderHub (e.g., https://mybinder.org)
  jupyterhub_url            : "https://jhub.dartmouth.edu/"  # The URL of the JupyterHub (e.g., https://datahub.berkeley.edu)
  thebe                     : false  # Add a thebe button to pages (requires the repository to run on Binder)
  colab_url                 : https://colab.research.google.com # The URL of Google Colab (e.g., https://colab.research.google.com)

repository:
  url                       : https://github.com/cosanlab/py-feat # The URL to your book's repository
  path_to_book              : "notebooks"  # A path to your book's folder, relative to the repository root.
  branch                    : master  # Which branch of the repository should be used when creating links

#######################################################################################
# Advanced and power-user settings
sphinx:
  extra_extensions          :   ['sphinx.ext.autodoc', 'sphinx.ext.napoleon'] # A list of extra extensions to load by Sphinx (added to those already used by JB).
  config                    :   # key-value pairs to directly over-ride the Sphinx configuration
